[metadata]
name = nicett6-pp81381
description = Nice TT6 tubular motor controller APIs
long_description = file: README.md
long_description_content_type = text/markdown
author = Phil Porter
url = https://github.com/pp81381/nicett6
classifiers=
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Topic :: Terminals :: Serial
    Topic :: Home Automation
    Framework :: AsyncIO
    Development Status :: 4 - Beta

[options]
packages = find:
python_requires = >=3.11
install_requires =
    pyserial>=3.5
    pyserial-asyncio-fast>=0.16

[options.packages.find]
exclude = tests*

[options.package_data]
nicett6 = py.typed
nicett6.emulator = config/*.json